version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    image: chrisfrill/messaging:0.1
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  client:
    image: nginx
    volumes:
      - ./client:/usr/share/nginx/html
    ports:
      - "8081:80"
